apiVersion: v1
kind: ServiceAccount
metadata: { name: inception, labels: { app: inception } }
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: { name: inception }
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: { name: inception }
subjects: [{ kind: ServiceAccount, name: inception }]
roleRef: { apiGroup: rbac.authorization.k8s.io, kind: Role, name: inception }
